---
- hosts: localhost
  become: true
  tasks:
  - name: Install python3-venv
    package:
      name: python3-venv
      state: present
  - name: Install Docker
    package:
      name: docker.io
      state: present
  - name: Install Gobuster
    package: 
      name: gobuster
      state: present
  - name: Install Seclists
    package:
      name: seclists
      state: present
  - name: Install Feroxbuster
    package:
      name: feroxbuster
      state: present
  - name: Install oscanner
    package:
      name: oscanner
      state: present
  - name: Install Redis Tools
    package:
      name: redis-tools
      state: present
  - name: Install sipvicious
    package:
      name: sipvicious 
      state: present
  - name: Install tnscmd10g
    package:
      name: tnscmd10g 
      state: present  
  - name: Install wkhtmltopdf
    package:
      name: wkhtmltopdf 
      state: present
  - name: Install xclip
    package:
      name: xclip 
      state: present
  - name: Install chisel
    package:
      name: chisel 
      state: present
  - name: Install mingw-w64
    package:
      name: mingw-w64 
      state: present
  - name: Install dconf-cli
    package:
      name: dconf-cli
      state: present
  - name: Install Sliver Server
    command: curl https://sliver.sh/install|sudo bash
    run_once: true
